name: love_swipe
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mysql1: ^0.20.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.4
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  flutter_local_notifications: ^12.0.4
  workmanager: ^0.5.2
  flutter_timezone: ^2.0.0
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/pay/


